### ISSUE TITLE
Preserve repository bulk data across service restart

### ISSUE THREAD

**Issue by Werkov** [ddiss/icyci#4]
### Current behavior

Each run of icyci daemon starts with a fresh workspace directory and that includes also the cloned repository. Restart of the daemon means the repository must be full re-cloned and that takes time (and space).

### Expected behavior

Only first start of daemon takes long time and repository data can be shared between different runs of icyci daemon.

Considered alternative: `git clone --depth=$c` but that's rather a workaround, e.g. kernel repo is quite large even without full history.

**Comment by ddiss** [comment]
Not quite what was asked for, but I've added the ability to specify a `-source-reference` repository, which gets passed through to `git clone --reference <src>`. This should significantly improve service restart and multi-instance resource consumption, but does require an existing mirror.
I'm in the process of dropping `-test-script` as a required argument, which should make it easy to setup local mirrors.

**Comment by Werkov** [comment]
I'm trying the `main` (fceb0fd) version and the reference doesn't seem to pass through:
icyci invocation:

    /home/mkoutny/icyci/icyci --source-repo https://token:@URL.git\
     --source-branch icyci-demo --test-script /home/mkoutny/kbuild-ci/test.sh \
     --results-repo https://token:@URL2.git --push-source-to-results true`
     --poll-interval 60 --source-reference /local/dir/linux.git

But the spawned command is:

    git clone --no-checkout --single-branch --branch icyci-demo https://token:URL.git \
    /tmp_dir/icyci-workspace7732677/source

Output is:
```
Jul 21 11:48:26 host icyci[125502]: 2023/07/21 11:48:26 transitioning from state 0: uninitialized -> 1: clone source repository
Jul 21 11:48:26 host icyci[125507]: Cloning into '/tmp_dir/icyci-workspace7732677/source'...
```

Any idea why it looks like the new arg isn't parsed?

**Comment by ddiss** [comment]
> Any idea why it looks like the new arg isn't parsed?

From a quick look at the codepath I'm not sure why the reference URL isn't being propagated through. Will take a closer look today. Thanks for the report.

**Comment by ddiss** [comment]
It looks like it's due to the callback style `flag.Func()` CLI parameter parsing coupled with `params` being pointer type. I've got a fix but want to also add some extra unit tests.

**Comment by ddiss** [comment]
> > Any idea why it looks like the new arg isn't parsed?
> 
> From a quick look at the codepath I'm not sure why the reference URL isn't being propagated through. Will take a closer look today. Thanks for the report.

This was actually a separate bug due to `--push-source-to-results` parameter syntax in the systemd file, which I split out into https://github.com/ddiss/icyci/issues/7 . It should now be working.

**Comment by ddiss** [comment]
Is the `-source-reference` functionality enough to consider closing this ticket?

**Comment by Werkov** [comment]
Yes. I've already benefited several times from the quicker (re)starts. Thanks!
